### ISSUE TITLE
Please publish to open-vsx for open source distributions of VS Code.

### ISSUE THREAD

**Issue by trusktr** [Shopify/vscode-as#19]
This extension is not available for VS Code that ships with various open source Linux distributions.

![Screenshot from 2021-02-08 16-51-34](https://user-images.githubusercontent.com/297678/107300219-e9971f80-6a2d-11eb-886f-96d6dca47bfb.png)

To make it available, you can publish to https://open-vsx.org, which is a place that host VS Code extensions that open source distributions connect their versions of VS Code to (in OSS distros, the name VS Code can't be used, so they change it. F.e. in Manjaro Linux the VS Code app is called "Code - OSS").

Here's the result for "assemblyscript" on open-vsx:

https://open-vsx.org/?search=assemblyscript&category=&sortBy=relevance&sortOrder=desc

That explains why I don't see it in my "Code - OSS" app. I just found out about open-vsx. Thought there was a bug.

**Comment by saulecabrera** [comment]
@trusktr the extension is now on open-vsx https://open-vsx.org/extension/saulecabrera/asls
