### ISSUE TITLE
asls not found

### ISSUE THREAD

**Issue by JerryGreen** [Shopify/vscode-as#20]
In my `package.json` I have the required `asbuild` command:

```json package
{
  "scripts": {
    "asbuild": "asc --extension as",
  }
}
```

When I run `yarn asbuild` it perfectly builds, and shows me errors:

![image](https://user-images.githubusercontent.com/13215662/112949920-255b8500-9153-11eb-8774-5e64c28f900c.png)

I use Windows so I installed `alpine-linux` via WSL, installed Nix there, and started the language server in Terminal:

![image](https://user-images.githubusercontent.com/13215662/112949418-a36b5c00-9152-11eb-8c51-f43f94999e28.png)

But still I'm getting this `asls not found` error in VSCode:

![image](https://user-images.githubusercontent.com/13215662/112949687-edecd880-9152-11eb-8c91-818323782288.png)

In console where I run `asls` I see no errors or anything when starting VSCode, though if I manually try to access `localhost:7658` in browser and then close the tab, it shut downs with error:

![image](https://user-images.githubusercontent.com/13215662/112952121-9603a100-9155-11eb-83b9-4b272da6e3b3.png)

So therefore it's not the issue with port forwarding or anything, but the extension itself, it seems. The version:

```
asls --version
v0.5.1
```

VSCode `saulecabrera.asls` version: `v0.3.3`

**Comment by saulecabrera** [comment]
@JerryGreen I've published https://github.com/Shopify/vscode-as/releases/tag/v0.4.0 which brings a couple of improvements, including improved support for WSL and less overhead during the setup. Could you confirm that this is working on your side?
